CREATE USER svetlana_nesenchuk
IDENTIFIED BY Nsn02984555 
DEFAULT TABLESPACE users 
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp 
PROFILE DEFAULT;

GRANT CONNECT, RESOURCE TO svetlana_nesenchuk;
GRANT CREATE VIEW TO svetlana_nesenchuk;
GRANT CREATE MATERIALIZED VIEW to svetlana_nesenchuk;
GRANT CREATE SYNONYM to svetlana_nesenchuk;